#!/usr/bin/env sh

source "${BASH_SOURCE%/*}/setup_init.sh"

source "${BASH_SOURCE%/*}/drop_database"

$psql -c "CREATE DATABASE $database_name"
$psql -c "CREATE USER $username NOCREATEDB NOCREATEUSER UNENCRYPTED PASSWORD '$password'"
