#!/usr/bin/env sh

# Set up Rails app. Run this script immediately after cloning the codebase.
# https://github.com/thoughtbot/guides/tree/master/protocol

# Exit if any subcommand fails
set -e

# Set up the database
# createuser -s obsidian || true

dropdb test_postgresql_connector || true

createdb test_postgresql_connector || true

psql -q test_postgresql_connector < test/setup/test_postgresql_connector.sql
