#!/bin/bash

source "${BASH_SOURCE%/*}/setup_init.sh"

database_count="$($psql -c "SELECT datname FROM pg_database" | grep $database_name | wc -l | xargs)"

if [ "$database_count" != 0 ]; then
  $psql -c "DROP DATABASE $database_name"
  $psql -c "DROP USER $username"
fi
